### PR TITLE
fix: add CI/CD Go github workflows

### PR DESCRIPTION
**Pull request by harshavardhana**
This PR adds CI/CD github workflows for Go
with 1.13.x and 1.14.x support, additionally
runs golang-ci linters to ensure code quality

### CODE REVIEW

**Comment by bcicen** [comment]
Thanks for the PR @harshavardhana -- propagating and handling an underlying reader error throughout every decoder method seems excessive, so I've used the existing scanner logic to [halt decoding and extend the decoder error with the underlying reader error here](https://github.com/bcicen/jstream/pull/11/files).

Please take a look and let me know if anything is missing from this solution.

Thanks as well for the CI/CD workflow -- if you can put this in a separate pull request, I'd be happy to merge.

**Comment by harshavardhana** [comment]
@ebozduman can you please look at the fix in the jstream master and it fixes the problem that we are facing?

**Comment by harshavardhana** [comment]
> Thanks for the PR @harshavardhana -- propagating and handling an underlying reader error throughout every decoder method seems excessive, so I've used the existing scanner logic to [halt decoding and extend the decoder error with the underlying reader error here](https://github.com/bcicen/jstream/pull/11/files).

Thank you @bcicen that seems like it might help and solve our issue. Would you mind adding a tag for a release as well for `go.mod` compatibility ?

**Comment by harshavardhana** [comment]
> Thanks as well for the CI/CD workflow -- if you can put this in a separate pull request, I'd be happy to merge.

Will do that thanks @bcicen

**Comment by harshavardhana** [comment]
updated this PR to be CI/CD workflow specific @bcicen

**Comment by bcicen** [comment]
@harshavardhana thanks! both merged and `v1.0.0` tag now pushed in master

**Pull request merged**
