### PR TITLE
Enable ObjectAsKVS() to preserve the input JSON key order

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by bcicen** [comment]
As JSON spec does not allow for ordered object keys, using a KV slice for objects would be an unexpected default and breaks current implementations.

Can you provide this behavior as a toggled option to Decoder (`ObjectsAsKV()`) while maintaining the default, `object()`->`map`?

**Comment by harshavardhana** [comment]
> As JSON spec does not allow for ordered object keys, using a KV slice for objects would be an unexpected default and breaks current implementations.
> 
> Can you provide this behavior as a toggled option to Decoder (`ObjectsAsKV()`) while maintaining the default, `object()`->`map`?

yes can do @bcicen

**Comment by harshavardhana** [comment]
Done @bcicen PTAL

**Comment by bcicen** [comment]
merged; thanks @harshavardhana

**Pull request merged**
