### PR TITLE
Add skip invalid json support from incoming stream

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by harshavardhana** [comment]
// cc @bcicen

**Comment by harshavardhana** [comment]
ping @bcicen - any reviews?

**Comment by bcicen** [comment]
this does not skip invalid json as much as just silently drop errors -- in your included test, four contiguous errors are hidden:

```skipped error: invalid character after object key:value pair: '3' [3,8]
skipped error: invalid character looking for beginning of value: ',' [3,19]
skipped error: invalid character looking for beginning of value: ':' [3,25]
skipped error: invalid character looking for beginning of value: '}' [3,36]
```
and disingenuous / incorrectly parsed data is being streamed as valid values
```
0	000	025	object | {"id":0,"key":"KAWJMGCD"}
0	026	062	object | {"id":950202005997,"key":"XNBQXYHX"}
0	064	072	object | {"id":0}
0	072	082	float    | 1291194748
0	082	083	nil       | null
0	083	088	string  | "key"
0	088	089	nil       | null
0	089	099	string  | "EWARYWJJ"
0	099	100	nil       | null
0	101	137	object | {"id":131291194748,"key":"EWARYWJJ"}
```
 
Skipping an error breaks depth tracking enough to where nested data are parsed as top-level documents, invalid syntax in one document can potentially alter/break the values of all  proceeding documents, etc.

If fatal errors are not surfaced, there needs to be some recovery logic to the decoder state and the invalid data should actually be skipped/dropped.

**Comment by harshavardhana** [comment]
Understood looks like its not possible cleanly @bcicen - thanks for clarifying. Closing this PR.

**Pull request closed without merging**
