### PR TITLE
enhance KV to include the type

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by harshavardhana** [comment]
Would you be able to take this in @bcicen? Do you have any concerns?

**Comment by bcicen** [comment]
@harshavardhana I will be versioning the library shortly in the future and am not sure the purpose of shadowing the built-in types makes sense. Can you provide a use case where the additional ValueType struct field provides benefit over a regular `switch mv.Value.(type) {`?

**Comment by harshavardhana** [comment]
The benefit is that for me to avoid reflection, since the internal code already did that,. Just exposing that value anyways.

**Comment by bcicen** [comment]
There's no reason to perform reflection -- the concrete value stored in the `MetaValue.Value` `interface{}` already has a defined type.

See the type switch [here](https://github.com/bcicen/jstream/blob/master/cmd/jstream/main.go#L33) and [benchmark](https://gist.github.com/bcicen/b532c2932ca341febab80e669768e21f) that provides results:

```
BenchmarkTypeSwitchPopulate-4   	  200000	      5775 ns/op	   16384 B/op	       1 allocs/op
BenchmarkTypeFieldPopulate-4    	  200000	      7352 ns/op	   24576 B/op	       1 allocs/op
BenchmarkTypeSwitch-4           	  300000	      3916 ns/op	       0 B/op	       0 allocs/op
BenchmarkTypeField-4            	  500000	      3619 ns/op	       0 B/op	       0 allocs/op
```

Indicating that the additional overhead from the `ValueType` field does not provide any simplification or performance benefit. Additionally, the `ValueType` field would only be available at the top-level of arrays and objects, so a type switch would still need to be performed on their contents.

**Comment by harshavardhana** [comment]
Yeah I am only interested in top level type, but I see your point I already did that where I am using this anyways.

**Pull request closed without merging**
